version: '3.8'

services:
    php:
        build:
            context: .
        container_name: symfony_php
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
    nginx:
        image: nginx:stable-alpine
        container_name: symfony_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
volumes:
    db_data:
